In [3]:

import numpy as np
import pandas as pd


In [8]:

# The csv does not contain header. The first 506 rows are the BCS maps' coordinates. The last ones are your new map coordinates.
mycsvfile1 = "00_2017_coordinates_wm_MOTparcels3d.csv"  # Coordinates of the white matter morphospace
data_csv1 = pd.read_csv(mycsvfile1, header=0, sep=';')  # Read the original coordinates file
mycsvfile2 = "coordinates_newMOT3d.csv"  # Coordinates of your maps, as projected onto the wm morphospace
data_csv2 = pd.read_csv(mycsvfile2, header=0, sep=';')  # Read the new maps' coordinates file

print(data_csv1.head())  # Check the first few rows of the first CSV
print(data_csv2.head())  # Check the first few rows of the second CSV
print(data_csv1.shape)  # Check the shape of the first CSV
print(data_csv2.shape)  # Check the shape of the second CSV

# Combine the 2 csv
data_csv = pd.concat([data_csv1, data_csv2], ignore_index=True)

print(data_csv.head())  # Display the first few rows of the data
print(data_csv.shape) 
print(data_csv.isna().sum())  # Count NaNs in each column
print(data_csv.isna().sum().sum())  # Total number of NaNs in the entire dataframe


          X         Y         Z
0  5.333868  3.737280  2.308684
1  6.130558  4.797709  3.204922
2  6.035204  4.548183  3.327650
3  6.233099  4.729073  3.302392
4  8.165491  4.984168  5.368546
           X         Y         Z
0   8.123353  6.083147  5.796643
1  10.198363  4.264278  7.956101
2  10.234671  4.201675  8.007011
3  10.137139  4.323755  7.874872
4   4.587162  4.802262  4.367787
(506, 3)
(3655, 3)
          X         Y         Z
0  5.333868  3.737280  2.308684
1  6.130558  4.797709  3.204922
2  6.035204  4.548183  3.327650
3  6.233099  4.729073  3.302392
4  8.165491  4.984168  5.368546
(4161, 3)
X    0
Y    0
Z    0
dtype: int64
0


In [9]:
print(data_csv.shape) 

(4161, 3)


In [6]:
# Convert to a NumPy array
coords = np.array(data_csv)

# Select the last n (according to the number of new maps, e.g. 200 maps) items
grid_coords = coords[-len(data_csv2):]  # The last rows are the new map coordinates
#grid_coords = np.nan_to_num(grid_coords)

original_coords = coords[:-len(data_csv2)]  # The first rows are the original coordinates

print(coords.shape)
print(grid_coords.shape)
print(original_coords.shape)
print("grid_coords shape:", coords.shape)
print("grid_coords preview:", coords[:5])  # Show first 5 rows
print("grid_coords shape:", grid_coords.shape)
print("grid_coords preview:", grid_coords[:5])  # Show first 5 rows
print("grid_coords shape:", original_coords.shape)
print("grid_coords preview:", original_coords[:5])  # Show first 5 rows




(4161, 3)
(3655, 3)
(506, 3)
grid_coords shape: (4161, 3)
grid_coords preview: [[5.33386755 3.73728013 2.30868363]
 [6.13055849 4.79770947 3.2049222 ]
 [6.03520393 4.54818344 3.32764959]
 [6.23309898 4.72907257 3.30239177]
 [8.1654911  4.98416758 5.36854601]]
grid_coords shape: (3655, 3)
grid_coords preview: [[ 8.123353    6.08314705  5.79664278]
 [10.1983633   4.26427794  7.95610142]
 [10.23467064  4.20167542  8.00701141]
 [10.13713932  4.32375526  7.87487173]
 [ 4.58716202  4.80226231  4.36778736]]
grid_coords shape: (506, 3)
grid_coords preview: [[5.33386755 3.73728013 2.30868363]
 [6.13055849 4.79770947 3.2049222 ]
 [6.03520393 4.54818344 3.32764959]
 [6.23309898 4.72907257 3.30239177]
 [8.1654911  4.98416758 5.36854601]]


In [7]:

# Initialize an empty list to hold the distances for all new maps
distances = []

# Calculate the Euclidean distances between new maps and original maps
for i, (x1, y1, z1) in enumerate(grid_coords):
    d = []
    for x2, y2, z2 in original_coords:
        # Calculate Euclidean distance
        distance = np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2 + (z1 - z2) ** 2)
        d.append(distance)

    # Append the distances for the current new map to the list
    distances.append(d)

# Convert the distances list to a NumPy array (for easier saving to CSV)
distances_array = np.array(distances)

# Save the result as a single CSV file
output_csv = "distances_from_new_maps_to_originalMOT.csv"
np.savetxt(output_csv, distances_array, delimiter=',')  # Save distances to CSV

print(f"Distances saved to {output_csv}")

Distances saved to distances_from_new_maps_to_originalMOT.csv
